const pictureConfig = {
  data: [
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9mxjp8.jpg" },
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9mxjp8.jpg" },
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9mxjp8.jpg" },
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9mxjp8.jpg" },
    { path: "https://w.wallhaven.cc/full/4l/wallhaven-4loyyp.jpg" },
    { path: "https://w.wallhaven.cc/full/48/wallhaven-4892ly.jpg" },
    { path: "https://w.wallhaven.cc/full/6q/wallhaven-6qr21l.jpg" },
    { path: "https://w.wallhaven.cc/full/0p/wallhaven-0pq7zm.jpg" },
    { path: "https://w.wallhaven.cc/full/4y/wallhaven-4y3kz7.jpg" },
    { path: "https://w.wallhaven.cc/full/wy/wallhaven-wyooq7.jpg" },
    { path: "https://w.wallhaven.cc/full/4l/wallhaven-4l695p.jpg" },
    { path: "https://w.wallhaven.cc/full/01/wallhaven-01v7z3.jpg" },
    { path: "https://w.wallhaven.cc/full/nm/wallhaven-nmddq1.jpg" },
    { path: "https://w.wallhaven.cc/full/nk/wallhaven-nkkwo6.jpg" },
    { path: "https://w.wallhaven.cc/full/0q/wallhaven-0qkwyd.jpg" },
    { path: "https://w.wallhaven.cc/full/73/wallhaven-73epv3.jpg" },
    { path: "https://w.wallhaven.cc/full/73/wallhaven-7316po.jpg" },
    { path: "https://w.wallhaven.cc/full/5w/wallhaven-5wpw75.jpg" },
    { path: "https://w.wallhaven.cc/full/48/wallhaven-48r3vj.png" },
    { path: "https://w.wallhaven.cc/full/j5/wallhaven-j55kgy.jpg" },
    { path: "https://w.wallhaven.cc/full/md/wallhaven-mdqqk8.jpg" },
    { path: "https://w.wallhaven.cc/full/zm/wallhaven-zmp62o.jpg" },
    { path: "https://w.wallhaven.cc/full/n6/wallhaven-n6wrv6.jpg" },
    { path: "https://w.wallhaven.cc/full/4l/wallhaven-4lee1p.jpg" },
    { path: "https://w.wallhaven.cc/full/kw/wallhaven-kw23q6.jpg" },
    { path: "https://w.wallhaven.cc/full/xl/wallhaven-xl92jd.jpg" },
    { path: "https://w.wallhaven.cc/full/0q/wallhaven-0q3l25.jpg" },
    { path: "https://w.wallhaven.cc/full/m9/wallhaven-m92m98.jpg" },
    { path: "https://w.wallhaven.cc/full/dp/wallhaven-dpp9qo.jpg" },
    { path: "https://w.wallhaven.cc/full/o3/wallhaven-o3gqe9.jpg" },
    { path: "https://w.wallhaven.cc/full/k7/wallhaven-k728q1.jpg" },
    { path: "https://w.wallhaven.cc/full/l8/wallhaven-l8y9yy.jpg" },
    { path: "https://w.wallhaven.cc/full/m9/wallhaven-m9m951.jpg" },
    { path: "https://w.wallhaven.cc/full/z8/wallhaven-z8d62v.jpg" },
    { path: "https://w.wallhaven.cc/full/m9/wallhaven-m919p1.jpg" },
    { path: "https://w.wallhaven.cc/full/l3/wallhaven-l3p2my.jpg" },
    { path: "https://w.wallhaven.cc/full/y8/wallhaven-y8d56x.jpg" },
    { path: "https://w.wallhaven.cc/full/y8/wallhaven-y8m2zk.jpg" },
    { path: "https://w.wallhaven.cc/full/ox/wallhaven-oxqv17.jpg" },
    { path: "https://w.wallhaven.cc/full/x8/wallhaven-x89p1d.jpg" },
    { path: "https://w.wallhaven.cc/full/m9/wallhaven-m9veoy.jpg" },
    { path: "https://w.wallhaven.cc/full/28/wallhaven-28xmyx.jpg" },
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9mm3y8.jpg" },
    { path: "https://w.wallhaven.cc/full/kx/wallhaven-kx9g3q.jpg" },
    { path: "https://w.wallhaven.cc/full/28/wallhaven-28pqoy.jpg" },
    { path: "https://w.wallhaven.cc/full/28/wallhaven-2857wg.jpg" },
    { path: "https://w.wallhaven.cc/full/o3/wallhaven-o36957.jpg" },
    { path: "https://w.wallhaven.cc/full/1k/wallhaven-1klg3w.jpg" },
    { path: "https://w.wallhaven.cc/full/85/wallhaven-855yoy.jpg" },
    { path: "https://w.wallhaven.cc/full/6o/wallhaven-6ogy27.jpg" },
    { path: "https://w.wallhaven.cc/full/q2/wallhaven-q2do3r.jpg" },
    { path: "https://w.wallhaven.cc/full/4d/wallhaven-4dww3l.jpg" },
    { path: "https://w.wallhaven.cc/full/8x/wallhaven-8xqk1j.jpg" },
    { path: "https://w.wallhaven.cc/full/j8/wallhaven-j8ql1y.jpg" },
    { path: "https://w.wallhaven.cc/full/vm/wallhaven-vmv8g3.jpg" },
    { path: "https://w.wallhaven.cc/full/j5/wallhaven-j5xp2w.jpg" },
    { path: "https://w.wallhaven.cc/full/qd/wallhaven-qdvgpr.jpg" },
    { path: "https://w.wallhaven.cc/full/49/wallhaven-49o1gk.jpg" },
    { path: "https://w.wallhaven.cc/full/6q/wallhaven-6qrq5q.jpg" },
    { path: "https://w.wallhaven.cc/full/lm/wallhaven-lmqwo2.jpg" },
    { path: "https://w.wallhaven.cc/full/vg/wallhaven-vg3eym.jpg" },
    { path: "https://w.wallhaven.cc/full/lm/wallhaven-lm569q.jpg" },
    { path: "https://w.wallhaven.cc/full/3k/wallhaven-3kd5yd.jpg" },
    { path: "https://w.wallhaven.cc/full/76/wallhaven-76zj3y.jpg" },
    { path: "https://w.wallhaven.cc/full/3k/wallhaven-3kpyk9.jpg" },
    { path: "https://w.wallhaven.cc/full/4l/wallhaven-4ll28r.jpg" },
    { path: "https://w.wallhaven.cc/full/r7/wallhaven-r7zj7m.jpg" },
    { path: "https://w.wallhaven.cc/full/lm/wallhaven-lmxy2l.jpg" },
    { path: "https://w.wallhaven.cc/full/6o/wallhaven-6oj156.jpg" },
    { path: "https://w.wallhaven.cc/full/z8/wallhaven-z8dg3o.jpg" },
    { path: "https://w.wallhaven.cc/full/1j/wallhaven-1j6qv9.jpg" },
    { path: "https://w.wallhaven.cc/full/lm/wallhaven-lmj82r.jpg" },
    { path: "https://w.wallhaven.cc/full/42/wallhaven-4251z9.jpg" },
    { path: "https://w.wallhaven.cc/full/yj/wallhaven-yj3q3d.jpg" },
    { path: "https://w.wallhaven.cc/full/1k/wallhaven-1ke811.jpg" },
    { path: "https://w.wallhaven.cc/full/x6/wallhaven-x6ejpd.jpg" },
    { path: "https://w.wallhaven.cc/full/yx/wallhaven-yxqgv7.jpg" },
    { path: "https://w.wallhaven.cc/full/o5/wallhaven-o5gl25.jpg" },
    { path: "https://w.wallhaven.cc/full/7p/wallhaven-7pj9dy.jpg" },
    { path: "https://w.wallhaven.cc/full/3l/wallhaven-3lqeo3.jpg" },
    { path: "https://w.wallhaven.cc/full/vq/wallhaven-vqp1j8.jpg" },
    { path: "https://w.wallhaven.cc/full/ex/wallhaven-ex8eyo.jpg" },
    { path: "https://w.wallhaven.cc/full/l8/wallhaven-l8y3zq.jpg" },
    { path: "https://w.wallhaven.cc/full/d6/wallhaven-d68kol.jpg" },
    { path: "https://w.wallhaven.cc/full/we/wallhaven-we5xjp.jpg" },
    { path: "https://w.wallhaven.cc/full/o5/wallhaven-o5gj5p.jpg" },
    { path: "https://w.wallhaven.cc/full/85/wallhaven-85gdok.jpg" },
    { path: "https://w.wallhaven.cc/full/x6/wallhaven-x6e75l.jpg" },
    { path: "https://w.wallhaven.cc/full/7p/wallhaven-7pjqve.jpg" },
    { path: "https://w.wallhaven.cc/full/jx/wallhaven-jxe5rq.jpg" },
    { path: "https://w.wallhaven.cc/full/qz/wallhaven-qzr8ol.jpg" },
    { path: "https://w.wallhaven.cc/full/5g/wallhaven-5gy7y1.jpg" },
    { path: "https://w.wallhaven.cc/full/vq/wallhaven-vqp3p3.jpg" },
    { path: "https://w.wallhaven.cc/full/2y/wallhaven-2y12p9.jpg" },
    { path: "https://w.wallhaven.cc/full/we/wallhaven-we5ll7.jpg" },
    { path: "https://w.wallhaven.cc/full/6d/wallhaven-6dlgj6.jpg" },
    { path: "https://w.wallhaven.cc/full/6d/wallhaven-6dldol.jpg" },
    { path: "https://w.wallhaven.cc/full/o5/wallhaven-o5gy6l.jpg" },
    { path: "https://w.wallhaven.cc/full/7p/wallhaven-7pjjp9.jpg" },
    { path: "https://w.wallhaven.cc/full/dg/wallhaven-dgg2ko.jpg" },
    { path: "https://w.wallhaven.cc/full/ne/wallhaven-neylmr.jpg" },
    { path: "https://w.wallhaven.cc/full/ox/wallhaven-oxy3qp.jpg" },
    { path: "https://w.wallhaven.cc/full/wy/wallhaven-wyjdgr.jpg" },
    { path: "https://w.wallhaven.cc/full/xl/wallhaven-xlj75z.jpg" },
    { path: "https://w.wallhaven.cc/full/yj/wallhaven-yjzwvl.jpg" },
    { path: "https://w.wallhaven.cc/full/m9/wallhaven-m92m98.jpg" },
    { path: "https://w.wallhaven.cc/full/4g/wallhaven-4gqldn.jpg" },
    { path: "https://w.wallhaven.cc/full/4o/wallhaven-4oj75n.jpg" },
    { path: "https://w.wallhaven.cc/full/43/wallhaven-43kjyv.jpg" },
    { path: "https://w.wallhaven.cc/full/4o/wallhaven-4o7mln.jpg" },
    { path: "https://w.wallhaven.cc/full/4o/wallhaven-4odmmn.jpg" },
    { path: "https://w.wallhaven.cc/full/z8/wallhaven-z8vkww.jpg" },
    { path: "https://w.wallhaven.cc/full/6o/wallhaven-6ogy27.jpg" },
    { path: "https://w.wallhaven.cc/full/x4/wallhaven-x4g87n.jpg" },
    { path: "https://w.wallhaven.cc/full/k7/wallhaven-k728q1.jpg" },
    { path: "https://w.wallhaven.cc/full/42/wallhaven-42ke59.jpg" },
    { path: "https://w.wallhaven.cc/full/42/wallhaven-428q94.jpg" },
    { path: "https://w.wallhaven.cc/full/49/wallhaven-492dk0.jpg" },
    { path: "https://w.wallhaven.cc/full/28/wallhaven-28xmyx.jpg" },
    { path: "https://w.wallhaven.cc/full/dp/wallhaven-dpp9qo.jpg" },
    { path: "https://w.wallhaven.cc/full/o3/wallhaven-o3gqe9.jpg" },
    { path: "https://w.wallhaven.cc/full/0j/wallhaven-0jx3pp.jpg" },
    { path: "https://w.wallhaven.cc/full/42/wallhaven-426wmn.jpg" },
    { path: "https://w.wallhaven.cc/full/5g/wallhaven-5gd6p9.jpg" },
    { path: "https://w.wallhaven.cc/full/43/wallhaven-432mqy.jpg" },
    { path: "https://w.wallhaven.cc/full/nz/wallhaven-nzdgg4.jpg" },
    { path: "https://w.wallhaven.cc/full/y8/wallhaven-y8q6vl.jpg" },
    { path: "https://w.wallhaven.cc/full/o3/wallhaven-o31jy9.jpg" },
    { path: "https://w.wallhaven.cc/full/g7/wallhaven-g7zzkl.jpg" },
    { path: "https://w.wallhaven.cc/full/5w/wallhaven-5we218.png" },
    { path: "https://w.wallhaven.cc/full/vg/wallhaven-vg8w65.jpg" },
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9m1wkd.png" },
    { path: "https://w.wallhaven.cc/full/ym/wallhaven-ymyp9k.jpg" },
    { path: "https://w.wallhaven.cc/full/1k/wallhaven-1kwqq9.jpg" },
    { path: "https://w.wallhaven.cc/full/rd/wallhaven-rdo85w.jpg" },
    { path: "https://w.wallhaven.cc/full/p8/wallhaven-p8vmd3.jpg" },
    { path: "https://w.wallhaven.cc/full/g8/wallhaven-g8mjjd.jpg" },
    { path: "https://w.wallhaven.cc/full/9m/wallhaven-9m7j1x.png" },
    { path: "https://w.wallhaven.cc/full/e7/wallhaven-e7mx9o.jpg" },
    { path: "https://w.wallhaven.cc/full/6d/wallhaven-6dorxl.jpg" },
    { path: "https://w.wallhaven.cc/full/13/wallhaven-13o7d1.jpg" },
    { path: "https://w.wallhaven.cc/full/z8/wallhaven-z8g5jj.jpg" },
    { path: "https://w.wallhaven.cc/full/2e/wallhaven-2er79g.jpg" },
    { path: "https://w.wallhaven.cc/full/qz/wallhaven-qzzojr.jpg" },
    { path: "https://w.wallhaven.cc/full/6o/wallhaven-6ow5vq.jpg" },
    { path: "https://w.wallhaven.cc/full/pk/wallhaven-pkmz23.jpg" },
    { path: "https://w.wallhaven.cc/full/0j/wallhaven-0j79y0.jpg" },
    ...[
      {
        id: "4dqpp3",
        url: "https://wallhaven.cc/w/4dqpp3",
        short_url: "https://whvn.cc/4dqpp3",
        views: 776,
        favorites: 25,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4000,
        dimension_y: 2541,
        resolution: "4000x2541",
        ratio: "1.57",
        file_size: 1056458,
        file_type: "image/jpeg",
        created_at: "2015-05-21 12:55:48",
        colors: ["#999999", "#cccccc", "#000000", "#ffffff", "#abbcda"],
        path: "https://w.wallhaven.cc/full/4d/wallhaven-4dqpp3.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/4d/4dqpp3.jpg",
          original: "https://th.wallhaven.cc/orig/4d/4dqpp3.jpg",
          small: "https://th.wallhaven.cc/small/4d/4dqpp3.jpg",
        },
      },
      {
        id: "j551zy",
        url: "https://wallhaven.cc/w/j551zy",
        short_url: "https://whvn.cc/j551zy",
        views: 784,
        favorites: 28,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4500,
        dimension_y: 2946,
        resolution: "4500x2946",
        ratio: "1.53",
        file_size: 1531465,
        file_type: "image/jpeg",
        created_at: "2018-09-15 11:28:52",
        colors: ["#ffffff", "#996633", "#424153", "#000000", "#999999"],
        path: "https://w.wallhaven.cc/full/j5/wallhaven-j551zy.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/j5/j551zy.jpg",
          original: "https://th.wallhaven.cc/orig/j5/j551zy.jpg",
          small: "https://th.wallhaven.cc/small/j5/j551zy.jpg",
        },
      },
      {
        id: "j5ygym",
        url: "https://wallhaven.cc/w/j5ygym",
        short_url: "https://whvn.cc/j5ygym",
        views: 745,
        favorites: 45,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4368,
        dimension_y: 2912,
        resolution: "4368x2912",
        ratio: "1.5",
        file_size: 1048374,
        file_type: "image/jpeg",
        created_at: "2019-08-31 19:25:51",
        colors: ["#999999", "#cccccc", "#996633", "#424153", "#cc6633"],
        path: "https://w.wallhaven.cc/full/j5/wallhaven-j5ygym.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/j5/j5ygym.jpg",
          original: "https://th.wallhaven.cc/orig/j5/j5ygym.jpg",
          small: "https://th.wallhaven.cc/small/j5/j5ygym.jpg",
        },
      },
      {
        id: "nkrld7",
        url: "https://wallhaven.cc/w/nkrld7",
        short_url: "https://whvn.cc/nkrld7",
        views: 1115,
        favorites: 37,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4096,
        dimension_y: 2731,
        resolution: "4096x2731",
        ratio: "1.5",
        file_size: 1149732,
        file_type: "image/jpeg",
        created_at: "2015-03-30 10:01:37",
        colors: ["#999999", "#424153", "#996633", "#cccccc", "#cc6633"],
        path: "https://w.wallhaven.cc/full/nk/wallhaven-nkrld7.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/nk/nkrld7.jpg",
          original: "https://th.wallhaven.cc/orig/nk/nkrld7.jpg",
          small: "https://th.wallhaven.cc/small/nk/nkrld7.jpg",
        },
      },
      {
        id: "2elqog",
        url: "https://wallhaven.cc/w/2elqog",
        short_url: "https://whvn.cc/2elqog",
        views: 766,
        favorites: 23,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 3888,
        dimension_y: 2592,
        resolution: "3888x2592",
        ratio: "1.5",
        file_size: 4133542,
        file_type: "image/jpeg",
        created_at: "2020-04-18 16:13:07",
        colors: ["#663300", "#424153", "#999999", "#cccccc", "#996633"],
        path: "https://w.wallhaven.cc/full/2e/wallhaven-2elqog.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/2e/2elqog.jpg",
          original: "https://th.wallhaven.cc/orig/2e/2elqog.jpg",
          small: "https://th.wallhaven.cc/small/2e/2elqog.jpg",
        },
      },
      {
        id: "nme8yy",
        url: "https://wallhaven.cc/w/nme8yy",
        short_url: "https://whvn.cc/nme8yy",
        views: 636,
        favorites: 25,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4000,
        dimension_y: 2708,
        resolution: "4000x2708",
        ratio: "1.48",
        file_size: 1230148,
        file_type: "image/jpeg",
        created_at: "2015-08-15 02:40:40",
        colors: ["#000000", "#424153", "#663300", "#660000", "#996633"],
        path: "https://w.wallhaven.cc/full/nm/wallhaven-nme8yy.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/nm/nme8yy.jpg",
          original: "https://th.wallhaven.cc/orig/nm/nme8yy.jpg",
          small: "https://th.wallhaven.cc/small/nm/nme8yy.jpg",
        },
      },
      {
        id: "4xx6mv",
        url: "https://wallhaven.cc/w/4xx6mv",
        short_url: "https://whvn.cc/4xx6mv",
        views: 938,
        favorites: 46,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5240,
        dimension_y: 2820,
        resolution: "5240x2820",
        ratio: "1.86",
        file_size: 1199567,
        file_type: "image/jpeg",
        created_at: "2016-01-17 00:04:23",
        colors: ["#ffffff", "#424153", "#e7d8b1", "#996633", "#999999"],
        path: "https://w.wallhaven.cc/full/4x/wallhaven-4xx6mv.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/4x/4xx6mv.jpg",
          original: "https://th.wallhaven.cc/orig/4x/4xx6mv.jpg",
          small: "https://th.wallhaven.cc/small/4x/4xx6mv.jpg",
        },
      },
      {
        id: "qdxd1d",
        url: "https://wallhaven.cc/w/qdxd1d",
        short_url: "https://whvn.cc/qdxd1d",
        views: 399,
        favorites: 6,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 6016,
        dimension_y: 4016,
        resolution: "6016x4016",
        ratio: "1.5",
        file_size: 11010707,
        file_type: "image/jpeg",
        created_at: "2018-01-02 00:48:35",
        colors: ["#ffffff", "#cccccc", "#e7d8b1", "#999999", "#000000"],
        path: "https://w.wallhaven.cc/full/qd/wallhaven-qdxd1d.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/qd/qdxd1d.jpg",
          original: "https://th.wallhaven.cc/orig/qd/qdxd1d.jpg",
          small: "https://th.wallhaven.cc/small/qd/qdxd1d.jpg",
        },
      },
      {
        id: "y873p7",
        url: "https://wallhaven.cc/w/y873p7",
        short_url: "https://whvn.cc/y873p7",
        views: 694,
        favorites: 37,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 3840,
        dimension_y: 5760,
        resolution: "3840x5760",
        ratio: "0.67",
        file_size: 2764326,
        file_type: "image/jpeg",
        created_at: "2020-11-12 23:22:28",
        colors: ["#999999", "#424153", "#996633", "#e7d8b1", "#000000"],
        path: "https://w.wallhaven.cc/full/y8/wallhaven-y873p7.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/y8/y873p7.jpg",
          original: "https://th.wallhaven.cc/orig/y8/y873p7.jpg",
          small: "https://th.wallhaven.cc/small/y8/y873p7.jpg",
        },
      },
      {
        id: "nr6emj",
        url: "https://wallhaven.cc/w/nr6emj",
        short_url: "https://whvn.cc/nr6emj",
        views: 1072,
        favorites: 30,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5616,
        dimension_y: 3744,
        resolution: "5616x3744",
        ratio: "1.5",
        file_size: 2453448,
        file_type: "image/jpeg",
        created_at: "2015-02-06 14:35:02",
        colors: ["#000000", "#663300", "#996633", "#424153", "#660000"],
        path: "https://w.wallhaven.cc/full/nr/wallhaven-nr6emj.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/nr/nr6emj.jpg",
          original: "https://th.wallhaven.cc/orig/nr/nr6emj.jpg",
          small: "https://th.wallhaven.cc/small/nr/nr6emj.jpg",
        },
      },
      {
        id: "x81wlv",
        url: "https://wallhaven.cc/w/x81wlv",
        short_url: "https://whvn.cc/x81wlv",
        views: 551,
        favorites: 29,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4000,
        dimension_y: 2668,
        resolution: "4000x2668",
        ratio: "1.5",
        file_size: 1529781,
        file_type: "image/jpeg",
        created_at: "2020-12-16 15:40:10",
        colors: ["#cccccc", "#ffffff", "#e7d8b1", "#999999", "#abbcda"],
        path: "https://w.wallhaven.cc/full/x8/wallhaven-x81wlv.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/x8/x81wlv.jpg",
          original: "https://th.wallhaven.cc/orig/x8/x81wlv.jpg",
          small: "https://th.wallhaven.cc/small/x8/x81wlv.jpg",
        },
      },
      {
        id: "gjyz6l",
        url: "https://wallhaven.cc/w/gjyz6l",
        short_url: "https://whvn.cc/gjyz6l",
        views: 634,
        favorites: 13,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5184,
        dimension_y: 3456,
        resolution: "5184x3456",
        ratio: "1.5",
        file_size: 1757817,
        file_type: "image/jpeg",
        created_at: "2017-12-31 16:44:26",
        colors: ["#999999", "#333399", "#ffffff", "#cccccc", "#424153"],
        path: "https://w.wallhaven.cc/full/gj/wallhaven-gjyz6l.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/gj/gjyz6l.jpg",
          original: "https://th.wallhaven.cc/orig/gj/gjyz6l.jpg",
          small: "https://th.wallhaven.cc/small/gj/gjyz6l.jpg",
        },
      },
      {
        id: "0q11yr",
        url: "https://wallhaven.cc/w/0q11yr",
        short_url: "https://whvn.cc/0q11yr",
        views: 804,
        favorites: 34,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4000,
        dimension_y: 2661,
        resolution: "4000x2661",
        ratio: "1.5",
        file_size: 1444237,
        file_type: "image/jpeg",
        created_at: "2016-01-10 03:24:53",
        colors: ["#000000", "#424153", "#999999", "#cccccc", "#abbcda"],
        path: "https://w.wallhaven.cc/full/0q/wallhaven-0q11yr.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/0q/0q11yr.jpg",
          original: "https://th.wallhaven.cc/orig/0q/0q11yr.jpg",
          small: "https://th.wallhaven.cc/small/0q/0q11yr.jpg",
        },
      },
      {
        id: "dpgjo3",
        url: "https://wallhaven.cc/w/dpgjo3",
        short_url: "https://whvn.cc/dpgjo3",
        views: 756,
        favorites: 38,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5000,
        dimension_y: 3334,
        resolution: "5000x3334",
        ratio: "1.5",
        file_size: 5903683,
        file_type: "image/jpeg",
        created_at: "2021-01-27 07:01:41",
        colors: ["#999999", "#e7d8b1", "#996633", "#424153", "#663300"],
        path: "https://w.wallhaven.cc/full/dp/wallhaven-dpgjo3.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/dp/dpgjo3.jpg",
          original: "https://th.wallhaven.cc/orig/dp/dpgjo3.jpg",
          small: "https://th.wallhaven.cc/small/dp/dpgjo3.jpg",
        },
      },
      {
        id: "3k1x69",
        url: "https://wallhaven.cc/w/3k1x69",
        short_url: "https://whvn.cc/3k1x69",
        views: 577,
        favorites: 20,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5066,
        dimension_y: 3378,
        resolution: "5066x3378",
        ratio: "1.5",
        file_size: 1724889,
        file_type: "image/jpeg",
        created_at: "2017-12-29 19:22:31",
        colors: ["#424153", "#996633", "#999999", "#cccccc", "#000000"],
        path: "https://w.wallhaven.cc/full/3k/wallhaven-3k1x69.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/3k/3k1x69.jpg",
          original: "https://th.wallhaven.cc/orig/3k/3k1x69.jpg",
          small: "https://th.wallhaven.cc/small/3k/3k1x69.jpg",
        },
      },
      {
        id: "eodgek",
        url: "https://wallhaven.cc/w/eodgek",
        short_url: "https://whvn.cc/eodgek",
        views: 640,
        favorites: 19,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5184,
        dimension_y: 3456,
        resolution: "5184x3456",
        ratio: "1.5",
        file_size: 1361770,
        file_type: "image/jpeg",
        created_at: "2018-05-30 19:04:38",
        colors: ["#e7d8b1", "#999999", "#000000", "#996633", "#cc6633"],
        path: "https://w.wallhaven.cc/full/eo/wallhaven-eodgek.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/eo/eodgek.jpg",
          original: "https://th.wallhaven.cc/orig/eo/eodgek.jpg",
          small: "https://th.wallhaven.cc/small/eo/eodgek.jpg",
        },
      },
      {
        id: "eod6dl",
        url: "https://wallhaven.cc/w/eod6dl",
        short_url: "https://whvn.cc/eod6dl",
        views: 739,
        favorites: 28,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4324,
        dimension_y: 2886,
        resolution: "4324x2886",
        ratio: "1.5",
        file_size: 749231,
        file_type: "image/jpeg",
        created_at: "2018-05-19 00:07:52",
        colors: ["#cccccc", "#999999", "#996633", "#424153", "#e7d8b1"],
        path: "https://w.wallhaven.cc/full/eo/wallhaven-eod6dl.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/eo/eod6dl.jpg",
          original: "https://th.wallhaven.cc/orig/eo/eod6dl.jpg",
          small: "https://th.wallhaven.cc/small/eo/eod6dl.jpg",
        },
      },
      {
        id: "nm5789",
        url: "https://wallhaven.cc/w/nm5789",
        short_url: "https://whvn.cc/nm5789",
        views: 723,
        favorites: 19,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 6000,
        dimension_y: 3829,
        resolution: "6000x3829",
        ratio: "1.57",
        file_size: 2215081,
        file_type: "image/jpeg",
        created_at: "2015-09-17 10:36:44",
        colors: ["#cccccc", "#000000", "#663300", "#e7d8b1", "#999999"],
        path: "https://w.wallhaven.cc/full/nm/wallhaven-nm5789.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/nm/nm5789.jpg",
          original: "https://th.wallhaven.cc/orig/nm/nm5789.jpg",
          small: "https://th.wallhaven.cc/small/nm/nm5789.jpg",
        },
      },
      {
        id: "k73y8q",
        url: "https://wallhaven.cc/w/k73y8q",
        short_url: "https://whvn.cc/k73y8q",
        views: 849,
        favorites: 60,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5000,
        dimension_y: 3333,
        resolution: "5000x3333",
        ratio: "1.5",
        file_size: 2833307,
        file_type: "image/jpeg",
        created_at: "2020-11-22 17:52:37",
        colors: ["#000000", "#424153", "#663300", "#999999", "#996633"],
        path: "https://w.wallhaven.cc/full/k7/wallhaven-k73y8q.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/k7/k73y8q.jpg",
          original: "https://th.wallhaven.cc/orig/k7/k73y8q.jpg",
          small: "https://th.wallhaven.cc/small/k7/k73y8q.jpg",
        },
      },
      {
        id: "k78p3q",
        url: "https://wallhaven.cc/w/k78p3q",
        short_url: "https://whvn.cc/k78p3q",
        views: 765,
        favorites: 36,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5616,
        dimension_y: 3744,
        resolution: "5616x3744",
        ratio: "1.5",
        file_size: 1559054,
        file_type: "image/jpeg",
        created_at: "2021-05-12 14:56:47",
        colors: ["#999999", "#abbcda", "#e7d8b1", "#cccccc", "#424153"],
        path: "https://w.wallhaven.cc/full/k7/wallhaven-k78p3q.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/k7/k78p3q.jpg",
          original: "https://th.wallhaven.cc/orig/k7/k78p3q.jpg",
          small: "https://th.wallhaven.cc/small/k7/k78p3q.jpg",
        },
      },
      {
        id: "ym7kl7",
        url: "https://wallhaven.cc/w/ym7kl7",
        short_url: "https://whvn.cc/ym7kl7",
        views: 759,
        favorites: 32,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 6000,
        dimension_y: 4000,
        resolution: "6000x4000",
        ratio: "1.5",
        file_size: 2313833,
        file_type: "image/jpeg",
        created_at: "2018-07-02 15:37:55",
        colors: ["#996633", "#999999", "#cccccc", "#e7d8b1", "#424153"],
        path: "https://w.wallhaven.cc/full/ym/wallhaven-ym7kl7.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/ym/ym7kl7.jpg",
          original: "https://th.wallhaven.cc/orig/ym/ym7kl7.jpg",
          small: "https://th.wallhaven.cc/small/ym/ym7kl7.jpg",
        },
      },
      {
        id: "83vejk",
        url: "https://wallhaven.cc/w/83vejk",
        short_url: "https://whvn.cc/83vejk",
        views: 705,
        favorites: 31,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 6720,
        dimension_y: 4480,
        resolution: "6720x4480",
        ratio: "1.5",
        file_size: 4476321,
        file_type: "image/jpeg",
        created_at: "2020-05-02 15:12:20",
        colors: ["#000000", "#424153", "#999999", "#996633", "#663300"],
        path: "https://w.wallhaven.cc/full/83/wallhaven-83vejk.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/83/83vejk.jpg",
          original: "https://th.wallhaven.cc/orig/83/83vejk.jpg",
          small: "https://th.wallhaven.cc/small/83/83vejk.jpg",
        },
      },
      {
        id: "qdxkyr",
        url: "https://wallhaven.cc/w/qdxkyr",
        short_url: "https://whvn.cc/qdxkyr",
        views: 755,
        favorites: 24,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 5212,
        dimension_y: 3468,
        resolution: "5212x3468",
        ratio: "1.5",
        file_size: 1930649,
        file_type: "image/jpeg",
        created_at: "2018-01-24 13:25:40",
        colors: ["#424153", "#000000", "#999999", "#663300", "#996633"],
        path: "https://w.wallhaven.cc/full/qd/wallhaven-qdxkyr.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/qd/qdxkyr.jpg",
          original: "https://th.wallhaven.cc/orig/qd/qdxkyr.jpg",
          small: "https://th.wallhaven.cc/small/qd/qdxkyr.jpg",
        },
      },
      {
        id: "vmoyl5",
        url: "https://wallhaven.cc/w/vmoyl5",
        short_url: "https://whvn.cc/vmoyl5",
        views: 1015,
        favorites: 42,
        source: "",
        purity: "nsfw",
        category: "people",
        dimension_x: 4232,
        dimension_y: 2854,
        resolution: "4232x2854",
        ratio: "1.48",
        file_size: 1074994,
        file_type: "image/jpeg",
        created_at: "2016-09-14 19:32:47",
        colors: ["#ffffff", "#e7d8b1", "#000000", "#999999", "#663300"],
        path: "https://w.wallhaven.cc/full/vm/wallhaven-vmoyl5.jpg",
        thumbs: {
          large: "https://th.wallhaven.cc/lg/vm/vmoyl5.jpg",
          original: "https://th.wallhaven.cc/orig/vm/vmoyl5.jpg",
          small: "https://th.wallhaven.cc/small/vm/vmoyl5.jpg",
        },
      },
    ],
  ],
};


module.exports = {
  pictureConfig
}